// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type Permission struct {
	PermissionID int64
	Name         string
}

type Role struct {
	RoleID int64
	Name   string
}

type RolePermission struct {
	RoleID       int64
	PermissionID int64
}

type User struct {
	UserID      int64
	LastName    string
	FirstName   string
	DisplayName string
	Email       string
}

type UserRole struct {
	UserID int64
	RoleID int64
}
