// Code generated by evercore; DO NOT EDIT.
package evercoregen_aggregates

const (
	OrganizationAggregateType = "OrganizationAggregate"
	OrganizationStateType = "OrganizationState"
	UserAggregateType = "UserAggregate"
)

var List = []string{
	OrganizationAggregateType,
	OrganizationStateType,
	UserAggregateType,
}


