// Code generated by evercore; DO NOT EDIT.
package evercoregen_aggregates

const (
	RoleAggregateType = "RoleAggregate"
	UserAggregateType = "UserAggregate"
)

var List = []string{
	RoleAggregateType,
	UserAggregateType,
}


