// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbsqlite

type Organization struct {
	ID         int64
	Name       string
	SystemName string
	Status     string
}

type Permission struct {
	ID         int64
	SystemName string
}

type ResourceType struct {
	ID         int64
	Name       string
	SystemName string
}

type Role struct {
	ID             int64
	OrganizationID int64
	Name           string
	SystemName     string
}

type RolePermission struct {
	RoleID       int64
	PermissionID int64
}

type User struct {
	ID          int64
	FirstName   string
	LastName    string
	DisplayName string
	Email       string
}

type UserRole struct {
	UserID         int64
	OrganizationID int64
	RoleID         int64
}
