// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbpostgres

import (
	"database/sql"
	"time"
)

type Organization struct {
	ID         int64
	Name       string
	SystemName string
	Status     string
}

type Role struct {
	ID             int64
	OrganizationID int64
	Name           string
	SystemName     string
}

type RolePermission struct {
	RoleID     int64
	Permission string
}

type User struct {
	ID          int64
	FirstName   string
	LastName    string
	DisplayName string
	Email       string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	LastLogin   sql.NullTime
	LoginCount  int32
	Verified    bool
}

type UserApiKey struct {
	ID         string
	SecretHash string
	Name       string
	UserID     int64
	CreatedAt  time.Time
	ExpiresAt  time.Time
}

type UserRole struct {
	UserID int64
	RoleID int64
}
