// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package dbpostgres

import (
	"context"
	"database/sql"
)

const addOrganization = `-- name: AddOrganization :exec
INSERT INTO organizations (id, name, system_name, status) 
VALUES ($1, $2, $3, $4)
`

type AddOrganizationParams struct {
	ID         int64
	Name       string
	SystemName string
	Status     string
}

// ---------------------------------------------------------------------------
//
// # Organization Management
//
// ---------------------------------------------------------------------------
func (q *Queries) AddOrganization(ctx context.Context, arg AddOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, addOrganization,
		arg.ID,
		arg.Name,
		arg.SystemName,
		arg.Status,
	)
	return err
}

const addPermissionToRole = `-- name: AddPermissionToRole :exec
INSERT INTO role_permissions (role_id, permission) 
VALUES ($1, $2)
`

type AddPermissionToRoleParams struct {
	RoleID     int64
	Permission string
}

func (q *Queries) AddPermissionToRole(ctx context.Context, arg AddPermissionToRoleParams) error {
	_, err := q.db.ExecContext(ctx, addPermissionToRole, arg.RoleID, arg.Permission)
	return err
}

const addRole = `-- name: AddRole :exec

INSERT INTO roles (id, organization_id, name, system_name) 
VALUES ($1, $2, $3, $4)
`

type AddRoleParams struct {
	ID             int64
	OrganizationID int64
	Name           string
	SystemName     string
}

// ---------------------------------------------------------------------------
//
// # Role Management
//
// ---------------------------------------------------------------------------
func (q *Queries) AddRole(ctx context.Context, arg AddRoleParams) error {
	_, err := q.db.ExecContext(ctx, addRole,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.SystemName,
	)
	return err
}

const addRoleToUser = `-- name: AddRoleToUser :exec
INSERT INTO user_roles (user_id, role_id) 
VALUES ($1, $2)
`

type AddRoleToUserParams struct {
	UserID int64
	RoleID int64
}

func (q *Queries) AddRoleToUser(ctx context.Context, arg AddRoleToUserParams) error {
	_, err := q.db.ExecContext(ctx, addRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const addUser = `-- name: AddUser :exec

INSERT INTO users (id, first_name, last_name, display_name, email, verified, created_at, updated_at) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type AddUserParams struct {
	ID          int64
	FirstName   string
	LastName    string
	DisplayName string
	Email       string
	Verified    bool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

// ---------------------------------------------------------------------------
//
// # User Management
//
// ---------------------------------------------------------------------------
func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.ExecContext(ctx, addUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.DisplayName,
		arg.Email,
		arg.Verified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const addUserToRole = `-- name: AddUserToRole :exec
INSERT INTO user_roles (user_id, role_id) 
VALUES ($1, $2)
`

type AddUserToRoleParams struct {
	UserID int64
	RoleID int64
}

func (q *Queries) AddUserToRole(ctx context.Context, arg AddUserToRoleParams) error {
	_, err := q.db.ExecContext(ctx, addUserToRole, arg.UserID, arg.RoleID)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const getAllUserOrganizationRoles = `-- name: GetAllUserOrganizationRoles :many
SELECT r.id, r.name, r.system_name, o.id as organization_id, o.name as organization_name, o.system_name as organization_system_name
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
JOIN organizations o ON o.id = r.organization_id
WHERE ur.user_id = $1
`

type GetAllUserOrganizationRolesRow struct {
	ID                     int64
	Name                   string
	SystemName             string
	OrganizationID         int64
	OrganizationName       string
	OrganizationSystemName string
}

func (q *Queries) GetAllUserOrganizationRoles(ctx context.Context, userID int64) ([]GetAllUserOrganizationRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUserOrganizationRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserOrganizationRolesRow
	for rows.Next() {
		var i GetAllUserOrganizationRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SystemName,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.OrganizationSystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, system_name, status FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SystemName,
		&i.Status,
	)
	return i, err
}

const getOrganizationBySystemName = `-- name: GetOrganizationBySystemName :one
SELECT id, name, system_name, status FROM organizations WHERE system_name = $1
`

func (q *Queries) GetOrganizationBySystemName(ctx context.Context, systemName string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationBySystemName, systemName)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SystemName,
		&i.Status,
	)
	return i, err
}

const getOrganizationRoles = `-- name: GetOrganizationRoles :many
SELECT r.id, r.name, r.system_name FROM roles r
WHERE r.organization_id = $1
`

type GetOrganizationRolesRow struct {
	ID         int64
	Name       string
	SystemName string
}

func (q *Queries) GetOrganizationRoles(ctx context.Context, organizationID int64) ([]GetOrganizationRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrganizationRoles, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrganizationRolesRow
	for rows.Next() {
		var i GetOrganizationRolesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SystemName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizations = `-- name: GetOrganizations :many
SELECT id, name, system_name FROM organizations
`

type GetOrganizationsRow struct {
	ID         int64
	Name       string
	SystemName string
}

func (q *Queries) GetOrganizations(ctx context.Context) ([]GetOrganizationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrganizationsRow
	for rows.Next() {
		var i GetOrganizationsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SystemName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT rp.permission FROM role_permissions rp
WHERE rp.role_id = $1
`

func (q *Queries) GetRolePermissions(ctx context.Context, roleID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolesForUser = `-- name: GetRolesForUser :many
SELECT r.id, r.name, r.system_name
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
`

type GetRolesForUserRow struct {
	ID         int64
	Name       string
	SystemName string
}

func (q *Queries) GetRolesForUser(ctx context.Context, userID int64) ([]GetRolesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRolesForUserRow
	for rows.Next() {
		var i GetRolesForUserRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SystemName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, first_name, last_name, display_name, email, verified FROM users WHERE id = $1
`

type GetUserRow struct {
	ID          int64
	FirstName   string
	LastName    string
	DisplayName string
	Email       string
	Verified    bool
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Email,
		&i.Verified,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, display_name, email, verified FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID          int64
	FirstName   string
	LastName    string
	DisplayName string
	Email       string
	Verified    bool
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Email,
		&i.Verified,
	)
	return i, err
}

const getUserOrganizationPermissions = `-- name: GetUserOrganizationPermissions :many
SELECT rp.permission FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
JOIN role_permissions rp ON rp.role_id = ur.role_id
WHERE ur.user_id = $1 AND r.organization_id = $2
`

type GetUserOrganizationPermissionsParams struct {
	UserID         int64
	OrganizationID int64
}

func (q *Queries) GetUserOrganizationPermissions(ctx context.Context, arg GetUserOrganizationPermissionsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserOrganizationPermissions, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserOrganizationRoles = `-- name: GetUserOrganizationRoles :many
SELECT r.id, r.name, r.system_name FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1 AND r.organization_id = $2
`

type GetUserOrganizationRolesParams struct {
	UserID         int64
	OrganizationID int64
}

type GetUserOrganizationRolesRow struct {
	ID         int64
	Name       string
	SystemName string
}

func (q *Queries) GetUserOrganizationRoles(ctx context.Context, arg GetUserOrganizationRolesParams) ([]GetUserOrganizationRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserOrganizationRoles, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserOrganizationRolesRow
	for rows.Next() {
		var i GetUserOrganizationRolesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SystemName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserOrganizations = `-- name: GetUserOrganizations :many
SELECT o.id, o.name, o.system_name 
FROM user_roles ur
LEFT JOIN roles r ON r.id = ur.role_id
LEFT JOIN organizations o ON o.id = r.organization_id
WHERE ur.user_id = $1
`

type GetUserOrganizationsRow struct {
	ID         sql.NullInt64
	Name       sql.NullString
	SystemName sql.NullString
}

func (q *Queries) GetUserOrganizations(ctx context.Context, userID int64) ([]GetUserOrganizationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserOrganizationsRow
	for rows.Next() {
		var i GetUserOrganizationsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SystemName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersInRole = `-- name: GetUsersInRole :many
SELECT u.id, u.first_name, u.last_name, u.display_name, u.email, u.verified
FROM user_roles ur
JOIN users u ON u.id = ur.user_id
WHERE ur.role_id = $1
`

type GetUsersInRoleRow struct {
	ID          int64
	FirstName   string
	LastName    string
	DisplayName string
	Email       string
	Verified    bool
}

func (q *Queries) GetUsersInRole(ctx context.Context, roleID int64) ([]GetUsersInRoleRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersInRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersInRoleRow
	for rows.Next() {
		var i GetUsersInRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DisplayName,
			&i.Email,
			&i.Verified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, system_name, status FROM organizations
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SystemName,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesWithUserCounts = `-- name: ListRolesWithUserCounts :many
SELECT r.id, r.name, r.system_name, count(ur.user_id) AS user_count
FROM roles r
LEFT JOIN user_roles ur ON ur.role_id=r.id
WHERE organization_id=$1
`

type ListRolesWithUserCountsRow struct {
	ID         int64
	Name       string
	SystemName string
	UserCount  int64
}

func (q *Queries) ListRolesWithUserCounts(ctx context.Context, organizationID int64) ([]ListRolesWithUserCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRolesWithUserCounts, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesWithUserCountsRow
	for rows.Next() {
		var i ListRolesWithUserCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SystemName,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrganizationRoles = `-- name: ListUserOrganizationRoles :many
SELECT o.id as organization_id, o.name as organization, 
	o.system_name as organization_system_name,
	r.id as role_id, r.name as role_name, r.system_name as role_system_name 
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
JOIN organizations o ON o.id = r.organization_id
WHERE ur.user_id = $1
`

type ListUserOrganizationRolesRow struct {
	OrganizationID         int64
	Organization           string
	OrganizationSystemName string
	RoleID                 int64
	RoleName               string
	RoleSystemName         string
}

func (q *Queries) ListUserOrganizationRoles(ctx context.Context, userID int64) ([]ListUserOrganizationRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserOrganizationRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserOrganizationRolesRow
	for rows.Next() {
		var i ListUserOrganizationRolesRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Organization,
			&i.OrganizationSystemName,
			&i.RoleID,
			&i.RoleName,
			&i.RoleSystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organizationsCount = `-- name: OrganizationsCount :one
SELECT COUNT(*) AS count FROM organizations
`

func (q *Queries) OrganizationsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, organizationsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const removeAllRolesFromUser = `-- name: RemoveAllRolesFromUser :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) RemoveAllRolesFromUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllRolesFromUser, userID)
	return err
}

const removePermissionFromRole = `-- name: RemovePermissionFromRole :exec
DELETE FROM role_permissions 
WHERE role_id = $1 AND permission = $2
`

type RemovePermissionFromRoleParams struct {
	RoleID     int64
	Permission string
}

func (q *Queries) RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error {
	_, err := q.db.ExecContext(ctx, removePermissionFromRole, arg.RoleID, arg.Permission)
	return err
}

const removeUserFromRole = `-- name: RemoveUserFromRole :exec
DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2
`

type RemoveUserFromRoleParams struct {
	UserID int64
	RoleID int64
}

func (q *Queries) RemoveUserFromRole(ctx context.Context, arg RemoveUserFromRoleParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromRole, arg.UserID, arg.RoleID)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations SET 
name = $1, 
system_name = $2,
status = $3
WHERE id = $4
`

type UpdateOrganizationParams struct {
	Name       string
	SystemName string
	Status     string
	ID         int64
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganization,
		arg.Name,
		arg.SystemName,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE roles SET 
name = $1, system_name = $2 WHERE id = $3
`

type UpdateRoleParams struct {
	Name       string
	SystemName string
	ID         int64
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateRole, arg.Name, arg.SystemName, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET first_name = $1, last_name = $2, display_name = $3, email = $4, verified = $5, updated_at = $6 WHERE id = $7
`

type UpdateUserParams struct {
	FirstName   string
	LastName    string
	DisplayName string
	Email       string
	Verified    bool
	UpdatedAt   sql.NullTime
	ID          int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.DisplayName,
		arg.Email,
		arg.Verified,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserLoginStats = `-- name: UpdateUserLoginStats :exec
UPDATE users 
SET last_login = $1, login_count = $2 
WHERE id = $3
`

type UpdateUserLoginStatsParams struct {
	LastLogin  sql.NullTime
	LoginCount int32
	ID         int64
}

func (q *Queries) UpdateUserLoginStats(ctx context.Context, arg UpdateUserLoginStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLoginStats, arg.LastLogin, arg.LoginCount, arg.ID)
	return err
}

const userSearch = `-- name: UserSearch :many
SELECT id, first_name, last_name, display_name, email, verified
FROM users
WHERE email ILIKE $1 OR disoplay_name ILIKE $1 LIMIT $3::int OFFSET $2::int
`

type UserSearchParams struct {
	Query string
	Start int32
	Count int32
}

type UserSearchRow struct {
	ID          int64
	FirstName   string
	LastName    string
	DisplayName string
	Email       string
	Verified    bool
}

func (q *Queries) UserSearch(ctx context.Context, arg UserSearchParams) ([]UserSearchRow, error) {
	rows, err := q.db.QueryContext(ctx, userSearch, arg.Query, arg.Start, arg.Count)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSearchRow
	for rows.Next() {
		var i UserSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DisplayName,
			&i.Email,
			&i.Verified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usersCount = `-- name: UsersCount :one
SELECT COUNT(*) AS count FROM users
`

func (q *Queries) UsersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, usersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
