// Code generated by evercore; DO NOT EDIT.
package evercoregen_events

const (
	UserCreatedEventType = "UserCreatedEvent"
	UserLoginFailedEventType = "UserLoginFailedEvent"
	UserLoginSucceededEventType = "UserLoginSucceededEvent"
	UserRolesUpdatedEventType = "UserRolesUpdatedEvent"
	UserUpdatedEventType = "UserUpdatedEvent"
	RoleCreatedEventType = "RoleCreatedEvent"
	RolePermissionAddedEventType = "RolePermissionAddedEvent"
	RolePermissionRemovedEventType = "RolePermissionRemovedEvent"
)

var List = []string{
	UserCreatedEventType,
	UserLoginFailedEventType,
	UserLoginSucceededEventType,
	UserRolesUpdatedEventType,
	UserUpdatedEventType,
	RoleCreatedEventType,
	RolePermissionAddedEventType,
	RolePermissionRemovedEventType,
}


