// Code generated by evercore; DO NOT EDIT.
package evercoregen

import (
	"github.com/kernelplex/evercore/base"

	events "github.com/kernelplex/ubase/lib/evercoregen/events"
	"github.com/kernelplex/ubase/lib/ubevents"
)

func StateEventDecoder(ev evercore.SerializedEvent) (evercore.EventState, error) {
	switch ev.EventType {

	// ================================================== 
	// State Events
	// ==================================================
	case events.UserCreatedEventType:
		eventState := ubevents.UserCreatedEvent {}
		err := evercore.DecodeEventStateTo(ev, &eventState)
		if err != nil {
			return nil, err
		}
		state := evercore.NewStateEvent(eventState)
		return state, nil
	case events.UserLoginFailedEventType:
		eventState := ubevents.UserLoginFailedEvent {}
		err := evercore.DecodeEventStateTo(ev, &eventState)
		if err != nil {
			return nil, err
		}
		state := evercore.NewStateEvent(eventState)
		return state, nil
	case events.UserLoginSucceededEventType:
		eventState := ubevents.UserLoginSucceededEvent {}
		err := evercore.DecodeEventStateTo(ev, &eventState)
		if err != nil {
			return nil, err
		}
		state := evercore.NewStateEvent(eventState)
		return state, nil
	case events.UserRolesUpdatedEventType:
		eventState := ubevents.UserRolesUpdatedEvent {}
		err := evercore.DecodeEventStateTo(ev, &eventState)
		if err != nil {
			return nil, err
		}
		state := evercore.NewStateEvent(eventState)
		return state, nil
	case events.UserUpdatedEventType:
		eventState := ubevents.UserUpdatedEvent {}
		err := evercore.DecodeEventStateTo(ev, &eventState)
		if err != nil {
			return nil, err
		}
		state := evercore.NewStateEvent(eventState)
		return state, nil
	}
	return nil, nil
}

func EventDecoder(ev evercore.SerializedEvent) (evercore.EventState, error) {
	switch ev.EventType {
	case events.RoleCreatedEventType:
		eventState := ubevents.RoleCreatedEvent {}
		err := evercore.DecodeEventStateTo(ev, &eventState)
		if err != nil {
			return nil, err
		}
		return &eventState, nil
	case events.RolePermissionAddedEventType:
		eventState := ubevents.RolePermissionAddedEvent {}
		err := evercore.DecodeEventStateTo(ev, &eventState)
		if err != nil {
			return nil, err
		}
		return &eventState, nil
	case events.RolePermissionRemovedEventType:
		eventState := ubevents.RolePermissionRemovedEvent {}
		err := evercore.DecodeEventStateTo(ev, &eventState)
		if err != nil {
			return nil, err
		}
		return &eventState, nil
	}
	return nil, nil
}

func init() {
	evercore.RegisterEventDecoder(
		StateEventDecoder,
		EventDecoder)
}
